version: '{build}'

branches:
    only:
        - master
        - /[0-9]+\.[0-9]+\.[0-9]+(-.+)?/

pull_requests:
    do_not_increment_build_number: true

environment:
    BUILD: $(APPVEYOR_BUILD_NUMBER)

build_script:
    - ps: ./build.ps1

test: off

artifacts:
    - path: .\artifacts\*\*
